# Generated by Django 2.0.5 on 2018-08-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='username',
            new_name='user_id',
        ),
    ]
