# Generated by Django 2.0.5 on 2018-08-30 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180830_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='transacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField(default='2')),
                ('balance', models.FloatField(default=0.0, max_length=30)),
                ('last_updated', models.DateTimeField(default='2018-04-04 12:00:00')),
                ('receiver', models.IntegerField(default=2)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='Amount',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transacion',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
