# Generated by Django 2.0.5 on 2018-08-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20180830_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transacion',
            new_name='transaction',
        ),
    ]
