# Generated by Django 2.0.5 on 2018-08-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20180830_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.EmailField(default='user@freelance.com', max_length=255),
        ),
    ]
