# Generated by Django 2.0.5 on 2018-08-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='username',
            field=models.CharField(default='remy', max_length=30),
        ),
    ]
