# Generated by Django 2.0.5 on 2018-08-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20180830_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='username',
        ),
    ]
