# Generated by Django 2.0.5 on 2018-06-04 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, max_length=255)),
                ('writer_email', models.EmailField(blank=True, max_length=254)),
                ('total', models.FloatField(default=5, max_length=255)),
                ('created_at', models.DateTimeField(default='2018-04-04 12:00:00')),
                ('status', models.CharField(default=1, max_length=10)),
                ('client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('Title', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField(blank=True, max_length=255)),
                ('timer', models.TimeField(default='12:00', max_length=20)),
                ('writer_email', models.EmailField(blank=True, max_length=254)),
                ('attachment', models.FileField(upload_to='freelance')),
                ('Number_of_pages', models.IntegerField(blank=True, default=3)),
                ('cost', models.FloatField(blank=True, max_length=255)),
                ('Message', models.CharField(max_length=255)),
                ('Accepted_status', models.CharField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Unknown')], default=3, max_length=3)),
                ('status', models.BooleanField(default=1, max_length=10)),
                ('created_at', models.DateTimeField()),
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('Title', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('attachment', models.FileField(upload_to='freelance')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('Number_of_pages', models.IntegerField(blank=True, default=3)),
                ('status', models.NullBooleanField(default=None, max_length=10)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
