# Generated by Django 2.0.5 on 2018-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='urlhash',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
