# Generated by Django 2.0.5 on 2018-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0003_auto_20180611_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='urlhash',
            field=models.CharField(blank=True, default='IMIMAV', max_length=6, null=True),
        ),
    ]
