# Generated by Django 2.0.5 on 2018-09-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0006_auto_20180907_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_cost',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='client_cost',
            name='status',
        ),
        migrations.AddField(
            model_name='client_cost',
            name='Balance',
            field=models.FloatField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='client_cost',
            name='Username',
            field=models.CharField(default='Name', max_length=255, verbose_name="Writer's username"),
        ),
        migrations.AddField(
            model_name='client_cost',
            name='paid',
            field=models.FloatField(default=0, max_length=255, verbose_name='Amount paid'),
        ),
        migrations.AlterField(
            model_name='client_cost',
            name='created_at',
            field=models.DateTimeField(default='2018-04-04 12:00:00', verbose_name='Last updated'),
        ),
        migrations.AlterField(
            model_name='client_cost',
            name='total',
            field=models.FloatField(default=0, max_length=255, verbose_name='Current earnings'),
        ),
    ]
