# Generated by Django 2.0.5 on 2018-09-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0007_auto_20180907_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='urlhash',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Reference Number'),
        ),
    ]
