# Generated by Django 2.0.5 on 2018-09-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0009_auto_20180910_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='status',
            field=models.NullBooleanField(default=1, max_length=10),
        ),
    ]
