# Generated by Django 2.0.5 on 2018-09-11 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelance', '0010_auto_20180910_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='circles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='Name', max_length=255, verbose_name="Writer's username")),
                ('created_at', models.DateTimeField(default='2018-04-04 12:00:00', verbose_name='Last updated')),
                ('status', models.NullBooleanField(default=0, max_length=10)),
                ('client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
