# Generated by Django 2.0.5 on 2018-09-12 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelance', '0011_circles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='circles',
            new_name='circle',
        ),
    ]
