# Generated by Django 2.0.5 on 2018-09-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0012_auto_20180912_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='cstatus',
            field=models.NullBooleanField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='circle',
            name='wstatus',
            field=models.NullBooleanField(default=1, max_length=10),
        ),
    ]
