# Generated by Django 2.0.5 on 2018-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0013_auto_20180913_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='cstatus',
            field=models.NullBooleanField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='circle',
            name='wstatus',
            field=models.NullBooleanField(default=0, max_length=10),
        ),
    ]
